services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wp_files:/var/www/html
    networks:
      - docker-network
    restart: always
    init: true

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wp_files:/var/www/html
    networks:
      - docker-network
    expose:
      - "9000"
    restart: always
    init: true
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - docker-network
    restart: always
    init: true

volumes:
  wp_db:
  wp_files:


networks:
  docker-network:
