services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wp_files:/var/www/html
    networks:
      - docker-network
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wp_files:/var/www/html
    networks:
      - docker-network
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - docker-network
    restart: always

volumes:
  wp_db:
  wp_files:


networks:
  docker-network:
