# /usr/bin/mysqld_safe --user=root

# sleep 5

# mariadb << EOF
# FLUSH PRIVILEGES ;
# USE mysql ;
# DROP DATABASE IF EXISTS test ;
# CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '$DB_ROOT_PASS';
# CREATE DATABASE IF NOT EXISTS $DB_NAME CHARACTER SET utf8 COLLATE utf8_general_ci ;
# FLUSH PRIVILEGES ;
# GRANT ALL ON $DB_NAME.* TO 'root'@'%' WITH GRANT OPTION ;
# CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED BY '$DB_PASS';
# GRANT ALL ON $DB_NAME.* TO '$DB_USER'@'%';
# FLUSH PRIVILEGES ;
# EOF

while true; do
	sleep 1
done